shared: &shared
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 10
  username: root
  password: root
  socket: /tmp/mysql.sock

development:
  database: matchtrak_dev
  <<: *shared

test:
  database: matchtrak_test
  <<: *shared


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: matchtrak
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock
