development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: matchtrak-dev
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: matchtrak
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock
